name: "Basic Tests"
on:
  pull_request:
  push:
jobs:
  nix-instantiate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: nix-instantiate ./release.nix --show-trace
  generate-keys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: nix-build ./release.nix -A testGenerateKeys --show-trace
